version: "3"
services:
  status-updater:
    image: iqtlabs/pibackbone-status-updater:stable
    restart: always
    networks:
      - pibackbone
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "LOCATION=${LOCATION}"
      - "WEBHOOK_URL=${WEBHOOK_URL}"
    volumes:
      - "/flash:/flash"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
    pibackbone:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 1400
