version: "3"
services:
  cell-sim7600g-h:
    image: iqtlabs/pibackbone-cell-sim7600g-h:stable
    restart: always
    network_mode: host
    privileged: true
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/gps:/flash/telemetry/gps"
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/sys:/sys"
      - "/var/tmp:/var/tmp"
    command:
      - ${APN}
      - ${GPS_CHECK}
