version: "3"
services:
  sense:
    image: iqtlabs/pibackbone-sense:stable
    restart: always
    network_mode: "none"
    privileged: true
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/sensors:/flash/telemetry/sensors"
      - "/flash/telemetry/status:/flash/telemetry/status"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
